export const ACTIONS = {
    LOAD_FEN: "LOAD_FEN",
    LOAD_PGN: "LOAD_PGN",
    UPDATE_BOARD_SIZE: "UPDATE_BOARD_SIZE",
    PIECE_CLICKED: "PIECE_CLICKED",
    PIECE_MOVED: "PIECE_MOVED",
    ROTATE_BOARD: "ROTATE_BOARD",
    TOGGLE_MARKINGS: "TOGGLE_MARKINGS",
    TOGGLE_MOVE_INDICATOR: "TOGGLE_MOVE_INDICATOR",
}