export const ACTIONS = {
    LOAD_FEN: "LOAD_FEN",
    LOAD_PGN: "LOAD_PGN",
    PIECE_CLICKED: "PIECE_CLICKED",
    PIECE_MOVED: "PIECE_MOVED",
    ROTATE_BOARD: "ROTATE_BOARD",
    TOGGLE_MARKINGS: "TOGGLE_MARKINGS",
    TOGGLE_MOVE_INDICATOR: "TOGGLE_MOVE_INDICATOR",
    SELECT_OPENING: "SELECT_OPENING",
    SET_VIEW: "SET_VIEW",
    PREVIOUS_MOVE: "PREVIOUS_MOVE",
    NEXT_MOVE: "NEXT_MOVE",
    FIRST_MOVE: "FIRST_MOVE",
    LATEST_MOVE: "LATEST_MOVE"
}